### ISSUE TITLE
Documentation link in README is dead

### ISSUE THREAD

**Issue by cthoyt** [saezlab/bioservices#1]

**Comment by mschubert** [comment]
This is just an idea, but how about highlighting the [cokelaer/bioservices](https://github.com/cokelaer/bioservices) here and removing that empty repo?

**Comment by npalacioescat** [comment]
That link is on actually the README of this repo and if we just remove it right now so it will the issue itself

**Comment by mschubert** [comment]
Yes, no reason to keep this repo
